# Generated by Django 2.2.2 on 2019-06-25 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DashboardUserprofileinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_site', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'dashboard_userprofileinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PmaBroadcast',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('applied', models.TextField(blank=True, null=True)),
                ('broadcastid', models.CharField(blank=True, db_column='broadcastId', max_length=255, null=True)),
                ('created', models.DateTimeField()),
                ('eligible', models.TextField(blank=True, null=True)),
                ('expirydate', models.DateTimeField(db_column='expiryDate')),
                ('overriddenby', models.CharField(blank=True, db_column='overriddenBy', max_length=255, null=True)),
                ('overridereason', models.CharField(blank=True, db_column='overrideReason', max_length=255, null=True)),
                ('emailsent', models.TextField(db_column='emailSent')),
                ('screened', models.TextField()),
            ],
            options={
                'db_table': 'pma_broadcast',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PmaContact',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('crmid', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('firstname', models.CharField(blank=True, db_column='firstName', max_length=255, null=True)),
                ('lastname', models.CharField(db_column='lastName', max_length=255)),
                ('mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('partner_fk', models.BigIntegerField()),
            ],
            options={
                'db_table': 'pma_contact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PmaDemand',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('active', models.TextField(blank=True, null=True)),
                ('bonddetails', models.CharField(blank=True, db_column='bondDetails', max_length=255, null=True)),
                ('bondduration', models.CharField(blank=True, db_column='bondDuration', max_length=255, null=True)),
                ('certification', models.CharField(blank=True, max_length=255, null=True)),
                ('compensation', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField()),
                ('enddate', models.DateTimeField(blank=True, db_column='endDate', null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('jobtitle', models.CharField(blank=True, db_column='jobTitle', max_length=255, null=True)),
                ('lastgradyear', models.CharField(blank=True, db_column='lastGradYear', max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('marks10', models.FloatField(blank=True, null=True)),
                ('marks12', models.FloatField(blank=True, null=True)),
                ('markspg', models.FloatField(blank=True, db_column='marksPG', null=True)),
                ('marksug', models.FloatField(blank=True, db_column='marksUG', null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('numberofpositions', models.IntegerField(blank=True, db_column='numberOfPositions', null=True)),
                ('specialconditions', models.CharField(blank=True, db_column='specialConditions', max_length=1000, null=True)),
                ('contact_fk', models.BigIntegerField()),
                ('partner_fk', models.BigIntegerField()),
                ('constraintlocation', models.CharField(db_column='constraintLocation', max_length=255)),
                ('jobdescription', models.CharField(blank=True, db_column='jobDescription', max_length=3000, null=True)),
                ('aptitudegrade', models.FloatField(db_column='aptitudeGrade')),
                ('communicationgrade', models.CharField(db_column='communicationGrade', max_length=255)),
                ('technicalgrade', models.FloatField(db_column='technicalGrade')),
                ('premium', models.TextField()),
                ('successindicatorscore', models.IntegerField(blank=True, db_column='successIndicatorScore', null=True)),
                ('applicationgap', models.IntegerField(blank=True, db_column='applicationGap', null=True)),
            ],
            options={
                'db_table': 'pma_demand',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PmaDemandDegrees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degrees', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'pma_demand_degrees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PmaDemandSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'pma_demand_skills',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PmaDrive',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'pma_drive',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PmaNotificationLikes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('likescount', models.BigIntegerField(db_column='likesCount')),
            ],
            options={
                'db_table': 'pma_notification_likes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PmaOffer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('drive_fk', models.BigIntegerField()),
                ('offerdate', models.DateField(blank=True, db_column='offerDate', null=True)),
            ],
            options={
                'db_table': 'pma_offer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PmaPartner',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=20)),
                ('crmid', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=100)),
                ('logourl', models.TextField(blank=True, db_column='logoUrl', null=True)),
                ('noofemployees', models.CharField(blank=True, db_column='noOfEmployees', max_length=20, null=True)),
                ('sector', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'pma_partner',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PmaPlacementCredits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainee_fk', models.BigIntegerField()),
                ('credits', models.IntegerField()),
                ('remarks', models.CharField(blank=True, max_length=50, null=True)),
                ('enteredby', models.CharField(blank=True, db_column='enteredBy', max_length=255, null=True)),
            ],
            options={
                'db_table': 'pma_placement_credits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PmaSelectionRound',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contactdetails', models.CharField(db_column='contactDetails', max_length=1500)),
                ('date', models.CharField(max_length=10)),
                ('roundnumber', models.IntegerField(db_column='roundNumber')),
                ('time', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'pma_selection_round',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PmaTrainee',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('batch', models.CharField(max_length=255)),
                ('certification', models.CharField(max_length=255)),
                ('communicationgrade', models.CharField(blank=True, db_column='communicationGrade', max_length=255, null=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('firstname', models.CharField(db_column='firstName', max_length=255)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('lastgradyear', models.IntegerField(db_column='lastGradYear')),
                ('lastgraduation', models.CharField(db_column='lastGraduation', max_length=255)),
                ('lastname', models.CharField(db_column='lastName', max_length=255)),
                ('marks10', models.FloatField()),
                ('marks12', models.FloatField()),
                ('markspg', models.FloatField(blank=True, db_column='marksPG', null=True)),
                ('marksug', models.FloatField(db_column='marksUG')),
                ('mobile', models.CharField(max_length=255, unique=True)),
                ('projectgrade', models.CharField(blank=True, db_column='projectGrade', max_length=255, null=True)),
                ('selfplacedwith', models.CharField(blank=True, db_column='selfPlacedWith', max_length=255, null=True)),
                ('skill', models.CharField(max_length=255)),
                ('technicalgrade', models.CharField(blank=True, db_column='technicalGrade', max_length=255, null=True)),
                ('traineeid', models.CharField(db_column='traineeId', max_length=255, unique=True)),
                ('verifiedby', models.CharField(blank=True, db_column='verifiedBy', max_length=255, null=True)),
                ('placed_partner_fk', models.BigIntegerField(blank=True, null=True)),
                ('enteredby', models.CharField(db_column='enteredBy', max_length=255)),
                ('updatedby', models.CharField(blank=True, db_column='updatedBy', max_length=255, null=True)),
                ('aptitudegrade', models.CharField(blank=True, db_column='aptitudeGrade', max_length=255, null=True)),
                ('inactive', models.TextField(db_column='inActive')),
                ('validfrom', models.DateField(blank=True, db_column='validFrom', null=True)),
                ('validto', models.DateField(blank=True, db_column='validTo', null=True)),
                ('currentlocation', models.CharField(db_column='currentLocation', max_length=255)),
                ('collegename', models.CharField(blank=True, db_column='collegeName', max_length=350, null=True)),
                ('dob', models.DateTimeField(blank=True, null=True)),
                ('yearofgrad', models.IntegerField(blank=True, db_column='yearOfGrad', null=True)),
                ('yearofinter', models.IntegerField(blank=True, db_column='yearOfInter', null=True)),
                ('yearofssc', models.IntegerField(blank=True, db_column='yearOfSSC', null=True)),
                ('offerdate', models.DateTimeField(blank=True, db_column='offerDate', null=True)),
                ('dateofjoining', models.CharField(blank=True, db_column='dateOfJoining', max_length=255, null=True)),
                ('backlogspg', models.IntegerField(db_column='backlogsPG')),
                ('backlogsug', models.IntegerField(db_column='backlogsUG')),
                ('collegenameug', models.CharField(db_column='collegeNameUG', max_length=255)),
                ('graduation', models.CharField(max_length=255)),
                ('interboardname', models.CharField(db_column='interBoardName', max_length=255)),
                ('rollnumberpg', models.CharField(blank=True, db_column='rollNumberPG', max_length=255, null=True)),
                ('rollnumberug', models.CharField(db_column='rollNumberUG', max_length=255)),
                ('sscboardname', models.CharField(db_column='sscBoardName', max_length=255)),
                ('universitypg', models.CharField(blank=True, db_column='universityPG', max_length=255, null=True)),
                ('universityug', models.CharField(db_column='universityUG', max_length=255)),
                ('yearofpg', models.IntegerField(blank=True, db_column='yearOfPG', null=True)),
                ('eamcetrank', models.CharField(db_column='eamcetRank', max_length=255)),
                ('photourl', models.CharField(blank=True, db_column='photoUrl', max_length=255, null=True)),
            ],
            options={
                'db_table': 'pma_trainee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PmaTraineeComment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('about', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('postedby', models.CharField(blank=True, db_column='postedBy', max_length=255, null=True)),
            ],
            options={
                'db_table': 'pma_trainee_comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PmaTraineeDrivesRemaining',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('remaining', models.IntegerField()),
            ],
            options={
                'db_table': 'pma_trainee_drives_remaining',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PmaTraineeRound',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('updatedby', models.CharField(db_column='updatedBy', max_length=255)),
            ],
            options={
                'db_table': 'pma_trainee_round',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PmaDriveRounds',
            fields=[
                ('drive', models.OneToOneField(db_column='Drive_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dashboard.PmaDrive')),
                ('rounds', models.CharField(blank=True, max_length=255, null=True)),
                ('round_num', models.IntegerField()),
            ],
            options={
                'db_table': 'pma_drive_rounds',
                'managed': False,
            },
        ),
    ]
