# Generated by Django 2.2.2 on 2019-06-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_dashbo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slno', models.IntegerField()),
                ('date', models.DateField()),
                ('partnerName', models.CharField(max_length=255)),
                ('jobTitle', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('certification', models.CharField(max_length=255)),
                ('yearLastGrad', models.CharField(max_length=255)),
                ('marksPG', models.IntegerField()),
                ('marksUG', models.IntegerField()),
                ('marks10', models.IntegerField()),
                ('marks12', models.IntegerField()),
                ('numberOfPos', models.IntegerField()),
                ('bondDetails', models.CharField(max_length=255)),
                ('bondDuration', models.CharField(max_length=255)),
                ('compensation', models.CharField(max_length=255)),
                ('workLocation', models.CharField(max_length=255)),
                ('constraintLocation', models.CharField(max_length=255)),
            ],
        ),
    ]
