# Generated by Django 2.2.2 on 2019-06-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_requirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfPlaced',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('batchid', models.CharField(max_length=255)),
                ('traineeid', models.IntegerField()),
                ('skills', models.CharField(max_length=255)),
                ('companyname', models.CharField(max_length=255)),
                ('emailid', models.CharField(max_length=255)),
                ('mobileno', models.BigIntegerField()),
                ('yearofgrad', models.IntegerField()),
                ('collegename', models.CharField(max_length=255)),
            ],
        ),
    ]
