# Generated by Django 2.2.2 on 2019-06-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_selfplaced'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveDrives',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('slno', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DrivesReport',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('roundNumber', models.IntegerField()),
                ('skills', models.CharField(max_length=255)),
                ('numberOfPositions', models.IntegerField()),
                ('compensation', models.IntegerField()),
                ('rounds', models.IntegerField()),
            ],
        ),
    ]
